# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Alperen Kopuz
email: alperenkopuz@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Embedded Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://akopuz.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  akopuz
repository: "akopuz/akopuz.github.io"

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale: "en-US"
title_separator: "|"
subtitle: "notepad of an embedded software engineer"
name: "Alperen Kopuz"
date_format: "%Y-%m-%d"
layout: single

plugins:
  - jekyll-feed

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      read_time: true

author:
  name     : "Alperen Kopuz"
  avatar   : 
  bio      : "My awesome biography constrained to a sentence or two goes here."
  location : "Istanbul, Turkey"